### ISSUE TITLE
Any documentation for this package?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [nickywoolf/carter#1]

**Comment by nickywoolf** [comment]
@abishekrsrikaanth Not yet. Should be able to get to work on it soon.

**Comment by abishekrsrikaanth** [comment]
@nickywoolf if you could just document the basics to jumpstart would be great

**Comment by nickywoolf** [comment]
@abishekrsrikaanth Added a README.

**Comment by Panoply** [comment]
Any documentation on initiating the get methods for products?

**Comment by nickywoolf** [comment]
@Panoply There isn't anything right now. Should be something in the next week or so.

**Comment by abishekrsrikaanth** [comment]
@nickywoolf :+1:

**Comment by nickywoolf** [comment]
[Product Resource](https://github.com/nickywoolf/carter/blob/master/src/Shopify/Resource/Product.php)

If you have a logged in user with valid `domain` and `access_token`, you can use.

```
<?php

$product = app()->make(Woolf\Carter\Shopify\Resource\Product::class);

$allProducts = $products->all();

$singleProduct = $product->get(123456);
```
