### ISSUE TITLE
Fails if New version is pushed.

### ISSUE THREAD

**Issue by Panoply** [nickywoolf/carter#3]
Strange error occurs. I'm not sure if this is an issue my end or the Applications end.

Setting up carter everything works fine! However, the moment you push changes to your production server on an already installed application Carter is failing. 

Here is the error logs:

```
View [shopify.escape_iframe] not found. (View: /srv/app/retailers/htdocs/resources/views/vendor/carter/shopify/auth/login.blade.php)
```
and 
```
InvalidArgumentException in FileViewFinder.php line 137:
View [shopify.escape_iframe] not found.
```

**Comment by nickywoolf** [comment]
@Panoply Can you check the file references the package view.

`/srv/app/retailers/htdocs/resources/views/vendor/carter/shopify/auth/login.blade.php`

First line should be: `@extends('carter::shopify.escape_iframe')`

**Comment by Panoply** [comment]
@nickywoolf This is happening via host (fortrabbit) but might be an issue on other hosts etc -- If i uninstall the application and delete the user record from database, from here install the app again everything will work as expected and the Carter startpage (dashboard) will appear. Now, lets say I make some amendments to the dashboard or app (the moment I push any for of change) and push new commits,  it will throw these errors.

I have cleared the cache and storage folders. My guess here it has something to do with the `signature.php` file. The partial is listed as `redirect_escape_iframe.blade.php` not `escape_iframe.` and the file on contains a redirect script. 

If I choose not to use the carter dashboard file and instead inject an auth `constructor` in a seperate controller and view directory then it will throw a signature.php error and tell me, `Undefined index: shop` however again it will work when installed but break when an update is made.

**Comment by nickywoolf** [comment]
@Panoply Just tagged a new version `1.1.3` that should fix this. Looks like I missed some things when I was doing some clean up - I need to get some tests in place.

Thanks for taking the time to point this out. Let me know if it's still not working for you.

**Comment by Panoply** [comment]
@nickywoolf Tack brother! This one fixed it. I love what you've done with this. It's the most fluent solution I've seen floating around. – I'm using it with my current project. Will yet you know if i come acoross anything else.
