### ISSUE TITLE
Redirection Issues

### ISSUE THREAD

**Issue by Panoply** [nickywoolf/carter#4]
Some redirection issues for non authenticated users when accessing these URL's outside of in-app redirection (so via the address bar):
- /login
- /dashboard
- /activate
- /register

If you load in incognito mode, and visit the url `/login` you get an `Undefined index: shop` error.
If you load in incognito mode and visit the url `/dashboard`  then you will get a redirection to the authorization URL address (this exposes app API KEY, scopes etc etc) -- e.g:

`https://admin/oauth/authorize?client_id=123abc&amp;scope=aaa,bbb&amp;redirect_uri=https://xxx.a/login`

If you load in `/activate` it will throw the: `Unable to parse URI: https:///admin/recurring_application_charges/.json` and lastly if load in `/register`  itwill throw the `Client Error: 403 - Invalid State`.  

In my application I don't use the `/vendor` directory really, only for authentication, signup, install etc. Instead I set my callback URL to another controller in the Shopify App settings. Inside this controller use an `auth` constructor:

```
    public function __construct()
    {
        $this->middleware('auth');
    }
```

This will (as in intended) redirect all unauthorized traffic to `/login` . The reason I mention this, is because most people will build outside of the `/vendor` directory and redirecting to `/signup would be a more viable. 

Hope this helps.

**Comment by nickywoolf** [comment]
@Panoply Made some progress on this. If you install or update from dev-master, you should see the changes.

Some method names have changed - if you run into any problems try removing the published config and views (if they exist).

- config/carter.php
- resources/views/vendor/carter

I'd welcome any feedback on the changes.

**Comment by Panoply** [comment]
Hey @nickywoolf! So here is what I come across recently. If user session expires, so say for example a user leaves their tab open for a period of time, the session expires and the "Signature"  fails, but there is no redirect in place.
